[tool.poetry]
name = "faq_demo"
version = "0.1.0"
description = ""
authors = ["George Panchuk"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
torch = "^1.10.1"
sentence-transformers = "^2.1.0"
quaterion = { git = "git@github.com:qdrant/quaterion.git", branch = "17-cache-dataloader-1" }
wandb = "^0.12.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
