[tool.poetry]
name = "faq_demo"
version = "0.1.0"
description = ""
authors = ["George Panchuk"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
torch = "^1.10.1"
sentence-transformers = "^2.1.0"
quaterion = { git = "git@github.com:qdrant/quaterion.git", branch = "25-cntr-loss-with-hard-samples" }
wandb = "^0.12.9"
pandas = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
